# ============================================
# Secret for MySQL Credentials
# Values are base64 encoded
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: phone-shop
type: Opaque
data:
  # Base64 encoded: echo -n "root" | base64 = cm9vdA==
  mysql-root-password: cm9vdA==
  mysql-user: cm9vdA==
  mysql-password: cm9vdA==

